name: navigation_stack
description: A set of helpers to make using Flutter Navigation 2.0 easier.
version: 0.0.7
homepage: https://github.com/tim-smart/flutter_navigation_stack

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fpdt: ^0.0.63
  riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
